import type { Metadata } from 'next';

export const siteConfig: Metadata = {
	appleWebApp: {
		title: 'NewTube',
	},
	authors: {
		name: 'Sanidhya Kumar Verma',
		url: 'https://github.com/sanidhyy',
	},
	description: 'AI-Powered YouTube Clone using Next.js 15 and Mux.',
	keywords: [
		'reactjs',
		'nextjs',
		'youtube',
		'youtube-clone',
		'yt-clone',
		'clerk-auth',
		'lucide-icons',
		'react-icons',
		'mux',
		'mux-player',
		'shadcn-ui',
		'radix-ui',
		'tailwindcss',
		'uploadthing',
		'upstash',
		'upstash-ratelimit',
		'upstash-redis',
		'ratelimit',
		'redis',
		'react-query',
		'openai',
		'player-style',
		'trpc',
		'drizzle-orm',
		'zod',
		'sonner',
		'typescript',
		'javascript',
		'vercel',
		'postcss',
		'prettier',
		'eslint',
		'react',
		'react-dom',
		'html',
		'css',
		'date-fns',
		'cn',
		'clsx',
		'lucide-react',
		'neon-db',
	] as Array<string>,
	title: 'NewTube | YouTube Clone',
} as const;

export const links = {
	sourceCode: 'https://github.com/sanidhyy/yt-clone',
} as const;
